version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
