CREATE TABLE todo_tasks (
    id SERIAL PRIMARY KEY,
    content VARCHAR NOT NULL,
    state INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
